// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Fresh hybrid keypair: 1216-byte public + 2432-byte private, laid out
/// `X25519_part ‖ MLKEM768_part`. Byte-compatible with the Dart
/// `HybridKemImpl.generateKeyPair()` wire format.
FrbHybridKeyPair hybridKeypair() =>
    RustPqcLib.instance.api.crateFrbApiHybridKeypair();

/// Encapsulate to a 1216-byte peer hybrid public key. Returns the 1120-byte
/// ciphertext and the 32-byte shared secret. Errors (as a Dart exception) on a
/// wrong-length key. Wire-compatible with the Dart `HybridKem.encapsulate()` — a
/// ciphertext from either side decapsulates on the other.
FrbEncapResult hybridEncap({required List<int> peerPublicKey}) =>
    RustPqcLib.instance.api
        .crateFrbApiHybridEncap(peerPublicKey: peerPublicKey);

/// Decapsulate a 1120-byte ciphertext with a 2432-byte hybrid private key →
/// 32-byte shared secret. Errors only on a wrong *length*; ML-KEM implicit
/// rejection (FIPS 203) means a tampered ciphertext yields a pseudo-random
/// secret (no error, no padding oracle). Byte-compatible with the Dart
/// `HybridKem.decapsulate()`.
Uint8List hybridDecap(
        {required List<int> ciphertext, required List<int> privateKey}) =>
    RustPqcLib.instance.api
        .crateFrbApiHybridDecap(ciphertext: ciphertext, privateKey: privateKey);

/// Deterministic, index-addressable 32-byte DM message key. Errors if
/// `epoch_secret` is not 32 bytes. Byte-for-byte identical to the Dart
/// `deriveDmMessageKey()` and `sk_pqc.derive_dm_message_key()` (shared HKDF
/// labels / KAT).
Uint8List deriveDmMessageKey(
        {required List<int> epochSecret,
        required int epoch,
        required int index}) =>
    RustPqcLib.instance.api.crateFrbApiDeriveDmMessageKey(
        epochSecret: epochSecret, epoch: epoch, index: index);

/// The hybrid suite identifier (`x25519-mlkem768`). Lets the Dart side assert it
/// is talking to the expected core. Matches the Dart `kSuiteId`.
String suiteId() => RustPqcLib.instance.api.crateFrbApiSuiteId();

/// The interop wire lengths, mirrored into Dart so the binding can self-check
/// against `SkPqcSizes`. Order: public, private, ciphertext, shared-secret.
List<int> wireSizes() => RustPqcLib.instance.api.crateFrbApiWireSizes();

/// The result of [`hybrid_encap`], mirrored into Dart by frb.
///
/// `ciphertext` is 1120 B (`X25519_eph_pub ‖ MLKEM768_ct`); `shared_secret` is
/// the 32-byte hybrid secret. Byte-compatible with the Dart `EncapResult`.
class FrbEncapResult {
  /// 1120-byte composite ciphertext.
  final Uint8List ciphertext;

  /// 32-byte hybrid shared secret.
  final Uint8List sharedSecret;

  const FrbEncapResult({
    required this.ciphertext,
    required this.sharedSecret,
  });

  @override
  int get hashCode => ciphertext.hashCode ^ sharedSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbEncapResult &&
          runtimeType == other.runtimeType &&
          ciphertext == other.ciphertext &&
          sharedSecret == other.sharedSecret;
}

/// A hybrid keypair, mirrored into Dart as a plain class by frb.
///
/// `public_key` is 1216 B (`X25519_pub ‖ MLKEM768_ek`); `private_key` is 2432 B
/// (`X25519_seed ‖ MLKEM768_dk`). Byte-compatible with the Dart `HybridKeyPair`
/// and `sk_pqc.hybrid_keypair()`.
class FrbHybridKeyPair {
  /// 1216-byte composite public key.
  final Uint8List publicKey;

  /// 2432-byte composite private key.
  final Uint8List privateKey;

  const FrbHybridKeyPair({
    required this.publicKey,
    required this.privateKey,
  });

  @override
  int get hashCode => publicKey.hashCode ^ privateKey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FrbHybridKeyPair &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          privateKey == other.privateKey;
}
