/// sk_pqc — **Rust core over FFI** (OPTIONAL flutter_rust_bridge binding).
///
/// This entrypoint backs the Dart `sk_pqc` API with the **same pure-Rust core**
/// as the Python services (the `sk-pqc-rs` crate: ML-KEM-768 via RustCrypto
/// `ml-kem` — **FIPS 203** — and X25519 via `x25519-dalek`), reached through
/// flutter_rust_bridge. It is the Dart twin of the proven PyO3 binding: ONE Rust
/// crypto core, byte-for-byte interoperable across Python, Rust, and Dart.
///
/// ## This is OPTIONAL and SEPARATE
/// Importing the default `package:sk_pqc/sk_pqc.dart` gives you the self-contained
/// Dart KEM + ratchet (liboqs / noble backends) with **no** Rust dependency.
/// This file is a *separate* import on purpose: it pulls in
/// `package:flutter_rust_bridge` and a compiled `sk-pqc-rs` cdylib, so only code
/// that wants the shared Rust core pays that cost.
///
/// ## Honest claims
/// `x25519-mlkem768` is a **hybrid** KEM: the 32-byte secret holds as long as
/// **either** the classical X25519 leg **or** the ML-KEM-768 leg holds. It is
/// **not** "quantum-proof". KEM-only (FIPS 203); signatures (FIPS 204 / ML-DSA)
/// are not part of this surface.
///
/// ## Loading the native library
/// Build the cdylib from the sibling crate with the `dart` feature:
/// ```sh
/// cd ../sk-pqc-rs && ~/.cargo/bin/cargo build --release --features dart
/// ```
/// Then either rely on the generated default loader (it looks in
/// `../sk-pqc-rs/target/release/`) via [SkPqcRustCore.ensureInitialized], or pass
/// an explicit `libraryPath` to the compiled `libsk_pqc.so` / `.dylib` / `.dll`.
library;

// `ExternalLibrary.open` (native dynamic-library loader) and `Uint8List` both
// come via the io-side generated surface. This binding is native-only (the
// codegen ran with `web: false`); web/wasm support is future work.
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'src/rust/frb_api.dart' as frb;
import 'src/rust/frb_generated.dart';
import 'src/types.dart';

export 'src/types.dart'
    show EncapResult, HybridKeyPair, SkPqcError, SkPqcSizes, kSuiteId;

/// The Rust-backed hybrid KEM + DM key-schedule, exposed with the SAME Dart
/// types as the pure-Dart backend so it is a drop-in alternative.
///
/// All methods are synchronous Rust calls (`#[frb(sync)]`) — no isolate hop —
/// after a one-time [ensureInitialized].
class SkPqcRustCore {
  SkPqcRustCore._();

  static bool _initialized = false;

  /// Load + initialize the Rust core exactly once (idempotent).
  ///
  /// Pass [libraryPath] to load a specific compiled `sk-pqc-rs` cdylib
  /// (`libsk_pqc.so` on Linux). With no path, the generated default loader is
  /// used (it expects `../sk-pqc-rs/target/release/`). Throws [SkPqcError] if
  /// the library cannot be loaded.
  static Future<void> ensureInitialized({String? libraryPath}) async {
    if (_initialized) return;
    try {
      if (libraryPath != null) {
        await RustPqcLib.init(
          externalLibrary: ExternalLibrary.open(libraryPath),
        );
      } else {
        await RustPqcLib.init();
      }
      _initialized = true;
    } catch (e) {
      throw SkPqcError('failed to initialize sk-pqc-rs core: $e');
    }
  }

  /// The suite identifier reported by the Rust core (`x25519-mlkem768`).
  static String get suiteId => frb.suiteId();

  /// The interop wire lengths the Rust core was built with, in the order
  /// `[public, private, ciphertext, sharedSecret]`. Used to self-check against
  /// [SkPqcSizes].
  static List<int> get wireSizes => frb.wireSizes();

  /// Fresh hybrid keypair (1216-byte public, 2432-byte private), generated by
  /// the Rust core. Wire-identical to the pure-Dart backend.
  static HybridKeyPair generateKeyPair() {
    final kp = frb.hybridKeypair();
    return HybridKeyPair(publicKey: kp.publicKey, privateKey: kp.privateKey);
  }

  /// Encapsulate to [peerPublicKey] (1216 B) via the Rust core. Returns the
  /// 1120-B ciphertext and 32-B shared secret. Throws [SkPqcError] on a
  /// wrong-length key.
  static EncapResult encapsulate(Uint8List peerPublicKey) {
    try {
      final r = frb.hybridEncap(peerPublicKey: peerPublicKey);
      return EncapResult(ciphertext: r.ciphertext, sharedSecret: r.sharedSecret);
    } on SkPqcError {
      rethrow;
    } catch (e) {
      throw SkPqcError('hybrid_encap failed: $e');
    }
  }

  /// Decapsulate [ciphertext] (1120 B) with [privateKey] (2432 B) via the Rust
  /// core → 32-B shared secret. ML-KEM implicit rejection (FIPS 203): a tampered
  /// ciphertext yields a pseudo-random secret, NOT an error. Only length/format
  /// errors throw [SkPqcError].
  static Uint8List decapsulate(Uint8List ciphertext, Uint8List privateKey) {
    try {
      return frb.hybridDecap(ciphertext: ciphertext, privateKey: privateKey);
    } on SkPqcError {
      rethrow;
    } catch (e) {
      throw SkPqcError('hybrid_decap failed: $e');
    }
  }

  /// Deterministic, index-addressable 32-byte DM message key from the Rust core.
  /// Byte-for-byte identical to the pure-Dart `deriveDmMessageKey` and the
  /// Python `sk_pqc.derive_dm_message_key` (shared HKDF labels / KAT). Throws
  /// [SkPqcError] if [epochSecret] is not 32 bytes.
  static Uint8List deriveDmMessageKey(
    Uint8List epochSecret,
    int epoch,
    int index,
  ) {
    try {
      return frb.deriveDmMessageKey(
        epochSecret: epochSecret,
        epoch: epoch,
        index: index,
      );
    } on SkPqcError {
      rethrow;
    } catch (e) {
      throw SkPqcError('derive_dm_message_key failed: $e');
    }
  }
}
